{% set version = '1.1.1.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dygraphs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dygraphs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dygraphs/dygraphs_{{ version }}.tar.gz
  sha256: c3d331f30012e721a048e04639f60ea738cd7e54e4f930ac9849b95f0f005208

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-htmltools >=0.3.5
    - r-htmlwidgets >=0.6
    - r-magrittr
    - r-xts >=0.9_7
    - r-zoo >=1.7_10

  run:
    - r-base
    - r-htmltools >=0.3.5
    - r-htmlwidgets >=0.6
    - r-magrittr
    - r-xts >=0.9_7
    - r-zoo >=1.7_10

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('dygraphs')"           # [not win]
    - "\"%R%\" -e \"library('dygraphs')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rstudio/dygraphs
  license: MIT + file LICENSE
  summary: An R interface to the 'dygraphs' JavaScript charting library (a copy of which is included
    in the package). Provides rich facilities for charting time-series data in R, including
    highly configurable series- and axis-display and interactive features like zoom/pan
    and series/point highlighting.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: dygraphs
# Type: Package
# Title: Interface to 'Dygraphs' Interactive Time Series Charting Library
# Version: 1.1.1.6
# Authors@R: c( person("Dan", "Vanderkam", role = c("aut", "cph"), comment = "dygraphs library in htmlwidgets/lib, http://dygraphs.com/"), person("Petr", "Shevtsov", role = c("cre", "cph"), email = "petr.shevtsov@gmail.com"), person("JJ", "Allaire", role = c("aut")), person(family = "RStudio", role = "cph"), person("Jonathan", "Owen", role = c("aut", "cph")), person("Daniel", "Gromer", role = c("aut", "cph")), person("Benoit", "Thieurmel", role = c("aut", "cph")), person("Kent", "Laukhuf", role = "ctb"), person(family = "jQuery Foundation", role = "cph", comment = "jQuery library"), person(family = "jQuery contributors", role = c("ctb", "cph"), comment = "jQuery library; authors listed in inst/htmlwidgets/lib/jquery/AUTHORS.txt") )
# URL: https://github.com/rstudio/dygraphs
# BugReports: https://github.com/rstudio/dygraphs/issues
# Description: An R interface to the 'dygraphs' JavaScript charting library (a copy of which is included in the package). Provides rich facilities for charting time-series data in R, including highly configurable series- and axis-display and interactive features like zoom/pan and series/point highlighting.
# License: MIT + file LICENSE
# Depends: R (>= 3.0)
# Imports: magrittr, htmlwidgets (>= 0.6), htmltools (>= 0.3.5), zoo (>= 1.7-10), xts (>= 0.9-7)
# Suggests: testthat
# Enhances: rmarkdown (>= 0.3.3), shiny (>= 0.10.2.1)
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-07-11 21:29:28 UTC; petr
# Author: Dan Vanderkam [aut, cph] (dygraphs library in htmlwidgets/lib, http://dygraphs.com/), Petr Shevtsov [cre, cph], JJ Allaire [aut], RStudio [cph], Jonathan Owen [aut, cph], Daniel Gromer [aut, cph], Benoit Thieurmel [aut, cph], Kent Laukhuf [ctb], jQuery Foundation [cph] (jQuery library), jQuery contributors [ctb, cph] (jQuery library; authors listed in inst/htmlwidgets/lib/jquery/AUTHORS.txt)
# Maintainer: Petr Shevtsov <petr.shevtsov@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-07-11 22:00:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
