travis:
  secure:
    BINSTAR_TOKEN: KOn+uv+x0pi+qU3k5wiy1WuyFN2jic47LPv7BrQBRMU9tILsLH5f207S/e4fSd4QLuuW2wNvph49Z1BaTzciIsFQMIa1aEtJkY4J/29BGJDaX5Rj2mIfMrMAQBh3oXPamSOBqn2P+Xz2V7YDseUkQLh6XWZpC0yXtM43q8W2WhrAX/ptC5bu6j+vnsg3wsK/109MwhRIPZHpowSMrLc5a4xQhdqoEz51VKVu3zR6sh6+nq+cE+LXub0XbO0DwIpyu5hmAEmTJEpX6BarLWD0jMgjL5rrOBZetbCZXfk5ZeeArXXWqnBVV/ha8Y1J9MZkUkTZcDKVU6N8Tma6EM7AReZ375UlQFZuKlczYC15cD55k3Z9Nh9MtaZjfqx83jg4HtgDBGk3xt3H/Evpnz1CwMZ1BJfhrH6swvjsyd3fL0CWuGxzH92GcDPhRDrlupfRtkVlLmXKsf4t3hQJC/Ux3VU8ddZa2RkGKuo2TDauJn4/6GjF3gRXpzKDXBYoxoRtqINZOeX/TRD/rFk2MqPEF3JO3Q5QztlKEZdKdgBktLYJXCFkMAj4WSHB378cPzwRQiMrDASSk6p3EvW1rvAk/Hd270g3238TiO6NFjqQTNLzZf7xtMF5h3hHy1MPRUAYAETxFewaBJXekzswtjgtC2gEZBF48KcaS0rFJy3ORhQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
