travis:
  secure:
    BINSTAR_TOKEN: HeRfezWPU0kMsPxxLahldCmUPVv8eMHxGkMyRd7hnLUxkY/okhdayAWUoagdH2fZx06nsSRhliIgAK59eQCPgW5nGom2ZAdJx7Zk102cX0GP1B5FwsMojTNsFU+lHl887iMM+Wnptbz6b1RGr3recuVb+5aNWqFwrKHfrmQXGpVeUK697qlfujy8UPK0s55nMJs0OmWjJa+7wAEBQQf+CB5PiNIS9r27JvYUYvpwYGM/SFjoYpvSENKEkWNv0uZr6CHlvTfVm39GdXrm6H1XqruzX1wsXmdI6uSMq4IJAT85wsWBC8C/aSFnvaz/QaXuNX4QtZfthLC8+Wu3DkmnHoI5l9X3OWma8RmgOUlfC3eAXW88TOjq1JmPTg39358jLzVL7epVAu29s077NG3OtIonwkxn5WEzbD7s7qQZgiPq9NmeelXbYfIi+hYAP/sLX6v4aVEI1xqCtC61rsE1h63Ag9sYgf+uAf2etlRYUfmblpO1fdAFli/JNG48gBWkmqvpGDyX8G4HK/c/ePzRvxDzJVGWMMTgNQJT10hF7KHNW0uqXvNN+6qgjweHxdqfV81Yb1e2thY80Eo0J7w8nHwakUUEfY5MibS3udEtRVzSm5JvX9G+BawZXOazEaTUyyRnmW7ipVZB+9TkBfFAJnyYrspipliDVUsX4Py3+YE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
