travis:
  secure:
    BINSTAR_TOKEN: mv0b76YnypDHl9sHuTxraCN37DK1y2mPxcVwum6jH3Rtk1o/3WKhn+gnO/FMIBKzyNjl+ftVNRCYSaUc5oLvju4CklRatrWo06t94Y7PIq8uaL+LIJIlYmNVgTb+LrCFJYutRKyQQfPhH2fo+kkSx/ZC+yrHODVB2KWSxsXgQpDFg8jN4M0NHhVlNy+N61bk0YL1RP78XqC32qbqvPnha2xExG0bj7btzIwtMZ7L8vq8R5Ej7pSN65jr7MAVmp+b01ID4kMaax7vwWhb0uTb1V+x8T1joofwiBa5kSHYbclK6VUo08abyEpxp57vJmLQTVCbHYr+FdQWvvMC+3IQ9Hg3yCZrh0VDRzHcrjFZ4W3AHJs8utjFZRuQ0sBCuply9oJW9A1yDX3qP5h621R5MHdBpnM+iVk2Qo3IxQbbXiC6BuX4jOirwm91Oo2JIICcVwPZi4PDux4T5hD3h1elbKnEEYbMikrNsHKT0NMr5mw/7pYdB78oS97hHWJg9TZufFCIYVaZD/pic2NXn73FdhG+zcqaBQvXWGdCZxklXtOBEynqd2lLN5O7bngONQTgp2RA4S0fanX582jksYQ8JuuKORdb+YxqAhIxhBr0FOmTH+rVRHtcx2ldrbOYf8FuWHEcTsC7ZnfdIXZrOlgM63qe5fxLzkgfqou2f7lsYlo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
